version: "3.8"

services:
  strapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - ../.env
    depends_on:
      - strapi-db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:strapi-db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  strapi-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi-db
      POSTGRES_USER: strapi-user
      POSTGRES_PASSWORD: strapi-pass
    volumes:
      - strapi-postgres-data:/var/lib/postgresql/data
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  strapi-postgres-data:
